---
- hosts: localhost

  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Place the index file at project root
      copy: src=index.html dest=/var/www/html/index.html owner=apache group=apache mode=0644

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
